dist: trusty
language: python
python:
- '3.5'
script:
- chmod +x package.sh
- ./package.sh
deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: sHzJCI8UfKvbIQrvz1U3+ss+fGm0RbUDXJbu4okj6mwp9TVffz4FML8ZVl84K8OdiXACmO4CRMsYl83GKXi0lfOH88zZMUBugywxf7/8/ayayxoUzAmaElZxM8Jxd4KzUMsMevtsTAvmH6UtHfXQWqjCxZrP3R/Tgwtz4HkGiFnLiVJG6pRtMiQshAyy97US+Ugkw4+bqFU2M/KzyeL4aFvnv+IlTmMSloCuRdkbX0vkkxnI/OGPdNmfF7Cmw1M7lFFf6E042mYbSTvonaT64Eaig5pBtL5z8BqZpT/NwjnzWhDsWwCZjxBO88Yd02OnYPxJLRi0lyHaim4Y+8roJA5TjR8DJawo1Nd33fMeF3j+bQ89H9ChEionUFeKbj2P3DDqEqOuH8db7KlSZopLLneoTS4yBvCZbs6jkw/JOdJln+e/y2sVzbtYFqYHf6d6ak2Svn/wTeIusaWyRCMZi0GuwCScA01dhvsjM7PbUIxyyjkeOtCiH0ytv9IEPL+5YGsU6+g1oQnOQ8kJaV/q2TWhITE8IlkzeXTdydIgs+xtjOfDiCK12+3icf3D4NDShQMgsiuZjrAu2IYJ9OqkCAbbGpdvkwoY1yjIC0Y5dO779XdE0thWftdQ3cFmK4fZFoqPEYbtPWgCS6ra/RHpHF3wWhLfdxyOjHkkJDdjF90=
  file:
   - riaps-pycom-amd64.deb 
   - riaps-pycom-armhf.deb
  skip_cleanup: true
  on:
    tags: true
